default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: postgres
  password: root  

development:
  <<: *default
  database: secret_mission_development

test:
  <<: *default
  database: secret_mission_test

production:
  <<: *default
  database: secret_mission_production